export const WORKTREE_ADD_TIMEOUT_MS = 180_000
export const WORKTREE_CREATE_AUXILIARY_GIT_TIMEOUT_MS = 5_000
export const WORKTREE_CREATE_ROLLBACK_TIMEOUT_MS = 30_000
// Two base probes, two base-config attempts, and two push-config attempts.
export const WORKTREE_ADD_MAX_AUXILIARY_GIT_COMMANDS = 6
export const WORKTREE_ADD_INNER_TIMEOUT_BUDGET_MS =
  WORKTREE_ADD_TIMEOUT_MS +
  WORKTREE_CREATE_AUXILIARY_GIT_TIMEOUT_MS * WORKTREE_ADD_MAX_AUXILIARY_GIT_COMMANDS
export const WORKTREE_ADD_TRANSPORT_TIMEOUT_MARGIN_MS = 5_000
export const WORKTREE_ADD_TRANSPORT_TIMEOUT_MS =
  WORKTREE_ADD_INNER_TIMEOUT_BUDGET_MS + WORKTREE_ADD_TRANSPORT_TIMEOUT_MARGIN_MS
export const WORKTREE_MATERIALIZATION_TIMEOUT_MS = WORKTREE_ADD_TIMEOUT_MS
// sparse init, sparse set, and forced checkout each own a subprocess timeout.
export const WORKTREE_MATERIALIZATION_GIT_COMMANDS = 3
export const WORKTREE_MATERIALIZATION_COMMAND_TRANSPORT_TIMEOUT_MS =
  WORKTREE_MATERIALIZATION_TIMEOUT_MS + WORKTREE_ADD_TRANSPORT_TIMEOUT_MARGIN_MS
export const WORKTREE_MATERIALIZATION_TRANSPORT_TIMEOUT_MS =
  WORKTREE_MATERIALIZATION_TIMEOUT_MS * WORKTREE_MATERIALIZATION_GIT_COMMANDS +
  WORKTREE_ADD_TRANSPORT_TIMEOUT_MARGIN_MS
// Two ref validations, two OID reads, ancestry, preferred+fallback worktree lists, and status/update-ref.
export const WORKTREE_LOCAL_BASE_REF_MAX_AUXILIARY_GIT_COMMANDS = 8
export const WORKTREE_LOCAL_BASE_REF_CHECK_INNER_TIMEOUT_BUDGET_MS =
  WORKTREE_CREATE_AUXILIARY_GIT_TIMEOUT_MS * WORKTREE_LOCAL_BASE_REF_MAX_AUXILIARY_GIT_COMMANDS
export const WORKTREE_LOCAL_BASE_REF_CHECK_TRANSPORT_TIMEOUT_MS =
  WORKTREE_LOCAL_BASE_REF_CHECK_INNER_TIMEOUT_BUDGET_MS + WORKTREE_ADD_TRANSPORT_TIMEOUT_MARGIN_MS
export const WORKTREE_LOCAL_BASE_REF_REFRESH_INNER_TIMEOUT_BUDGET_MS =
  WORKTREE_LOCAL_BASE_REF_CHECK_INNER_TIMEOUT_BUDGET_MS + WORKTREE_MATERIALIZATION_TIMEOUT_MS
export const WORKTREE_LOCAL_BASE_REF_REFRESH_TRANSPORT_TIMEOUT_MS =
  WORKTREE_LOCAL_BASE_REF_REFRESH_INNER_TIMEOUT_BUDGET_MS + WORKTREE_ADD_TRANSPORT_TIMEOUT_MARGIN_MS
